/** @file cmdline.h
 *  @brief The header file for the command line option parser
 *  generated by GNU Gengetopt version 2.23
 *  http://www.gnu.org/software/gengetopt.
 *  DO NOT modify this file, since it can be overwritten
 *  @author GNU Gengetopt */

#ifndef CMDLINE_H
#define CMDLINE_H

/* If we use autoconf.  */
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <stdio.h> /* for FILE */

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#ifndef CMDLINE_PARSER_PACKAGE
/** @brief the program name (used for printing errors) */
#define CMDLINE_PARSER_PACKAGE "clc-viz"
#endif

#ifndef CMDLINE_PARSER_PACKAGE_NAME
/** @brief the complete program name (used for help and version) */
#define CMDLINE_PARSER_PACKAGE_NAME "clc-viz"
#endif

#ifndef CMDLINE_PARSER_VERSION
/** @brief the program version */
#define CMDLINE_PARSER_VERSION "0.0.6"
#endif

/** @brief Where the command line options are stored */
struct gengetopt_args_info
{
  const char *help_help; /**< @brief Print help and exit help description.  */
  const char *version_help; /**< @brief Print version and exit help description.  */
  char * text_arg;	/**< @brief Reference(s) file.  */
  char * text_orig;	/**< @brief Reference(s) file original value given at command line.  */
  const char *text_help; /**< @brief Reference(s) file help description.  */
  char * query_arg;	/**< @brief Query sequences file.  */
  char * query_orig;	/**< @brief Query sequences file original value given at command line.  */
  const char *query_help; /**< @brief Query sequences file help description.  */
  char * mode_arg;	/**< @brief Chaining mode (global/semiglobal) (default='global').  */
  char * mode_orig;	/**< @brief Chaining mode (global/semiglobal) original value given at command line.  */
  const char *mode_help; /**< @brief Chaining mode (global/semiglobal) help description.  */
  char * anchor_type_arg;	/**< @brief (MUM/MEM) (default='MUM').  */
  char * anchor_type_orig;	/**< @brief (MUM/MEM) original value given at command line.  */
  const char *anchor_type_help; /**< @brief (MUM/MEM) help description.  */
  int anchor_length_arg;	/**< @brief Minimum anchor length (default='20').  */
  char * anchor_length_orig;	/**< @brief Minimum anchor length original value given at command line.  */
  const char *anchor_length_help; /**< @brief Minimum anchor length help description.  */
  int all_to_all_flag;	/**< @brief Pairwise comparisons (queries) (default=off).  */
  const char *all_to_all_help; /**< @brief Pairwise comparisons (queries) help description.  */
  int chainx_flag;	/**< @brief Chain with at-cg/ChainX original algorithm (default=off).  */
  const char *chainx_help; /**< @brief Chain with at-cg/ChainX original algorithm help description.  */
  int chainx_opt_flag;	/**< @brief Chain with algbio/ChainX optimal algorithm (default=off).  */
  const char *chainx_opt_help; /**< @brief Chain with algbio/ChainX optimal algorithm help description.  */
  char * output_arg;	/**< @brief Output each optimal chain in MUMmer-like format {ref start, query start, length} (1-based).  */
  char * output_orig;	/**< @brief Output each optimal chain in MUMmer-like format {ref start, query start, length} (1-based) original value given at command line.  */
  const char *output_help; /**< @brief Output each optimal chain in MUMmer-like format {ref start, query start, length} (1-based) help description.  */
  char * sam_arg;	/**< @brief Output approximate alignment based on the optimal chain (SAM format).  */
  char * sam_orig;	/**< @brief Output approximate alignment based on the optimal chain (SAM format) original value given at command line.  */
  const char *sam_help; /**< @brief Output approximate alignment based on the optimal chain (SAM format) help description.  */
  int store_SAM_sequence_flag;	/**< @brief Store the query sequence in the SAM output (default=off).  */
  const char *store_SAM_sequence_help; /**< @brief Store the query sequence in the SAM output help description.  */
  int chainx_original_magic_numbers_flag;	/**< @brief In ChainX mode, use original magic numbers B = 100, alpha = 4 instead of variable B >= 100, alpha = 4 (default=off).  */
  const char *chainx_original_magic_numbers_help; /**< @brief In ChainX mode, use original magic numbers B = 100, alpha = 4 instead of variable B >= 100, alpha = 4 help description.  */
  char * custom_anchors_arg;	/**< @brief Do not index/query but read the anchors from this file (NB it should respect the same order as query file).  */
  char * custom_anchors_orig;	/**< @brief Do not index/query but read the anchors from this file (NB it should respect the same order as query file) original value given at command line.  */
  const char *custom_anchors_help; /**< @brief Do not index/query but read the anchors from this file (NB it should respect the same order as query file) help description.  */
  long random_anchors_arg;	/**< @brief Number of random anchors to generate (default='-1').  */
  char * random_anchors_orig;	/**< @brief Number of random anchors to generate original value given at command line.  */
  const char *random_anchors_help; /**< @brief Number of random anchors to generate help description.  */
  char * debug_case_two_output_file_arg;	/**< @brief Visualize case 2 in this file (BMP format) (default='').  */
  char * debug_case_two_output_file_orig;	/**< @brief Visualize case 2 in this file (BMP format) original value given at command line.  */
  const char *debug_case_two_output_file_help; /**< @brief Visualize case 2 in this file (BMP format) help description.  */
  int random_seed_arg;	/**< @brief Seed for the PRNG (-1 is different at every invocation) (default='-1').  */
  char * random_seed_orig;	/**< @brief Seed for the PRNG (-1 is different at every invocation) original value given at command line.  */
  const char *random_seed_help; /**< @brief Seed for the PRNG (-1 is different at every invocation) help description.  */
  
  unsigned int help_given ;	/**< @brief Whether help was given.  */
  unsigned int version_given ;	/**< @brief Whether version was given.  */
  unsigned int text_given ;	/**< @brief Whether text was given.  */
  unsigned int query_given ;	/**< @brief Whether query was given.  */
  unsigned int mode_given ;	/**< @brief Whether mode was given.  */
  unsigned int anchor_type_given ;	/**< @brief Whether anchor-type was given.  */
  unsigned int anchor_length_given ;	/**< @brief Whether anchor-length was given.  */
  unsigned int all_to_all_given ;	/**< @brief Whether all-to-all was given.  */
  unsigned int chainx_given ;	/**< @brief Whether chainx was given.  */
  unsigned int chainx_opt_given ;	/**< @brief Whether chainx-opt was given.  */
  unsigned int output_given ;	/**< @brief Whether output was given.  */
  unsigned int sam_given ;	/**< @brief Whether sam was given.  */
  unsigned int store_SAM_sequence_given ;	/**< @brief Whether store-SAM-sequence was given.  */
  unsigned int chainx_original_magic_numbers_given ;	/**< @brief Whether chainx-original-magic-numbers was given.  */
  unsigned int custom_anchors_given ;	/**< @brief Whether custom-anchors was given.  */
  unsigned int random_anchors_given ;	/**< @brief Whether random-anchors was given.  */
  unsigned int debug_case_two_output_file_given ;	/**< @brief Whether debug-case-two-output-file was given.  */
  unsigned int random_seed_given ;	/**< @brief Whether random-seed was given.  */

  char **inputs ; /**< @brief unnamed options (options without names) */
  unsigned inputs_num ; /**< @brief unnamed options number */
} ;

/** @brief The additional parameters to pass to parser functions */
struct cmdline_parser_params
{
  int override; /**< @brief whether to override possibly already present options (default 0) */
  int initialize; /**< @brief whether to initialize the option structure gengetopt_args_info (default 1) */
  int check_required; /**< @brief whether to check that all required options were provided (default 1) */
  int check_ambiguity; /**< @brief whether to check for options already specified in the option structure gengetopt_args_info (default 0) */
  int print_errors; /**< @brief whether getopt_long should print an error message for a bad option (default 1) */
} ;

/** @brief the purpose string of the program */
extern const char *gengetopt_args_info_purpose;
/** @brief the usage string of the program */
extern const char *gengetopt_args_info_usage;
/** @brief the description string of the program */
extern const char *gengetopt_args_info_description;
/** @brief all the lines making the help output */
extern const char *gengetopt_args_info_help[];

/**
 * The command line parser
 * @param argc the number of command line options
 * @param argv the command line options
 * @param args_info the structure where option information will be stored
 * @return 0 if everything went fine, NON 0 if an error took place
 */
int cmdline_parser (int argc, char **argv,
  struct gengetopt_args_info *args_info);

/**
 * The command line parser (version with additional parameters - deprecated)
 * @param argc the number of command line options
 * @param argv the command line options
 * @param args_info the structure where option information will be stored
 * @param override whether to override possibly already present options
 * @param initialize whether to initialize the option structure my_args_info
 * @param check_required whether to check that all required options were provided
 * @return 0 if everything went fine, NON 0 if an error took place
 * @deprecated use cmdline_parser_ext() instead
 */
int cmdline_parser2 (int argc, char **argv,
  struct gengetopt_args_info *args_info,
  int override, int initialize, int check_required);

/**
 * The command line parser (version with additional parameters)
 * @param argc the number of command line options
 * @param argv the command line options
 * @param args_info the structure where option information will be stored
 * @param params additional parameters for the parser
 * @return 0 if everything went fine, NON 0 if an error took place
 */
int cmdline_parser_ext (int argc, char **argv,
  struct gengetopt_args_info *args_info,
  struct cmdline_parser_params *params);

/**
 * Save the contents of the option struct into an already open FILE stream.
 * @param outfile the stream where to dump options
 * @param args_info the option struct to dump
 * @return 0 if everything went fine, NON 0 if an error took place
 */
int cmdline_parser_dump(FILE *outfile,
  struct gengetopt_args_info *args_info);

/**
 * Save the contents of the option struct into a (text) file.
 * This file can be read by the config file parser (if generated by gengetopt)
 * @param filename the file where to save
 * @param args_info the option struct to save
 * @return 0 if everything went fine, NON 0 if an error took place
 */
int cmdline_parser_file_save(const char *filename,
  struct gengetopt_args_info *args_info);

/**
 * Print the help
 */
void cmdline_parser_print_help(void);
/**
 * Print the version
 */
void cmdline_parser_print_version(void);

/**
 * Initializes all the fields a cmdline_parser_params structure 
 * to their default values
 * @param params the structure to initialize
 */
void cmdline_parser_params_init(struct cmdline_parser_params *params);

/**
 * Allocates dynamically a cmdline_parser_params structure and initializes
 * all its fields to their default values
 * @return the created and initialized cmdline_parser_params structure
 */
struct cmdline_parser_params *cmdline_parser_params_create(void);

/**
 * Initializes the passed gengetopt_args_info structure's fields
 * (also set default values for options that have a default)
 * @param args_info the structure to initialize
 */
void cmdline_parser_init (struct gengetopt_args_info *args_info);
/**
 * Deallocates the string fields of the gengetopt_args_info structure
 * (but does not deallocate the structure itself)
 * @param args_info the structure to deallocate
 */
void cmdline_parser_free (struct gengetopt_args_info *args_info);

/**
 * Checks that all the required options were specified
 * @param args_info the structure to check
 * @param prog_name the name of the program that will be used to print
 *   possible errors
 * @return
 */
int cmdline_parser_required (struct gengetopt_args_info *args_info,
  const char *prog_name);


#ifdef __cplusplus
}
#endif /* __cplusplus */
#endif /* CMDLINE_H */
