/*
  File autogenerated by gengetopt version 2.23
  generated with the following command:
  gengetopt --input=./src/command-line-parsing/config.ggo --output-dir=./src/command-line-parsing/ --unnamed-opts 

  The developers of gengetopt consider the fixed text that goes in all
  gengetopt output files to be in the public domain:
  we make no copyright claims on it.
*/

/* If we use autoconf.  */
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#ifndef FIX_UNUSED
#define FIX_UNUSED(X) (void) (X) /* avoid warnings for unused params */
#endif

#include <getopt.h>

#include "cmdline.h"

const char *gengetopt_args_info_purpose = "Verification, WIP implementation, and visualization of linearithmic-time\ncolinear chaining";

const char *gengetopt_args_info_usage = "Usage: clc-viz [-m global/semiglobal] [-a MUM/MEM] [-l minanchorlength] [-t\ntext.fasta(.gz)] [-q query.fasta(.gz)] [--chainx|--chainx-opt]\n[--chainx-original-magic-numbers] [-o out.mummer] [--sam out.sam]\n[--store-SAM-sequence] [--custom-anchors anchors.mummer] [--all-to-all]\n[--random-anchors ANCHORNUM] [-g gap-gap-ld.bmp] [-r INT]";

const char *gengetopt_args_info_versiontext = "";

const char *gengetopt_args_info_description = "";

const char *gengetopt_args_info_help[] = {
  "  -h, --help                    Print help and exit",
  "  -V, --version                 Print version and exit",
  "  -t, --text=PATH               Reference(s) file",
  "  -q, --query=PATH              Query sequences file",
  "  -m, --mode=MODE               Chaining mode (global/semiglobal)\n                                  (default=`global')",
  "  -a, --anchor-type=ANCHOR      (MUM/MEM)  (default=`MUM')",
  "  -l, --anchor-length=LENGTH    Minimum anchor length  (default=`20')",
  "      --all-to-all              Pairwise comparisons (queries)  (default=off)",
  "      --chainx                  Chain with at-cg/ChainX original algorithm\n                                  (default=off)",
  "      --chainx-opt              Chain with algbio/ChainX optimal algorithm\n                                  (default=off)",
  "  -o, --output=PATH             Output each optimal chain in MUMmer-like format\n                                  {ref start, query start, length} (1-based)",
  "      --sam=PATH                Output approximate alignment based on the\n                                  optimal chain (SAM format)",
  "      --store-SAM-sequence      Store the query sequence in the SAM output\n                                  (default=off)",
  "      --chainx-original-magic-numbers\n                                In ChainX mode, use original magic numbers B =\n                                  100, alpha = 4 instead of variable B >= 100,\n                                  alpha = 4  (default=off)",
  "      --custom-anchors=PATH     Do not index/query but read the anchors from\n                                  this file (NB it should respect the same\n                                  order as query file)",
  "      --random-anchors=ANCHORNUM\n                                Number of random anchors to generate\n                                  (default=`-1')",
  "  -g, --debug-case-two-output-file=BMPFILE\n                                Visualize case 2 in this file (BMP format)\n                                  (default=`')",
  "  -r, --random-seed=INT         Seed for the PRNG (-1 is different at every\n                                  invocation)  (default=`-1')",
    0
};

typedef enum {ARG_NO
  , ARG_FLAG
  , ARG_STRING
  , ARG_INT
  , ARG_LONG
} cmdline_parser_arg_type;

static
void clear_given (struct gengetopt_args_info *args_info);
static
void clear_args (struct gengetopt_args_info *args_info);

static int
cmdline_parser_internal (int argc, char **argv, struct gengetopt_args_info *args_info,
                        struct cmdline_parser_params *params, const char *additional_error);


static char *
gengetopt_strdup (const char *s);

static
void clear_given (struct gengetopt_args_info *args_info)
{
  args_info->help_given = 0 ;
  args_info->version_given = 0 ;
  args_info->text_given = 0 ;
  args_info->query_given = 0 ;
  args_info->mode_given = 0 ;
  args_info->anchor_type_given = 0 ;
  args_info->anchor_length_given = 0 ;
  args_info->all_to_all_given = 0 ;
  args_info->chainx_given = 0 ;
  args_info->chainx_opt_given = 0 ;
  args_info->output_given = 0 ;
  args_info->sam_given = 0 ;
  args_info->store_SAM_sequence_given = 0 ;
  args_info->chainx_original_magic_numbers_given = 0 ;
  args_info->custom_anchors_given = 0 ;
  args_info->random_anchors_given = 0 ;
  args_info->debug_case_two_output_file_given = 0 ;
  args_info->random_seed_given = 0 ;
}

static
void clear_args (struct gengetopt_args_info *args_info)
{
  FIX_UNUSED (args_info);
  args_info->text_arg = NULL;
  args_info->text_orig = NULL;
  args_info->query_arg = NULL;
  args_info->query_orig = NULL;
  args_info->mode_arg = gengetopt_strdup ("global");
  args_info->mode_orig = NULL;
  args_info->anchor_type_arg = gengetopt_strdup ("MUM");
  args_info->anchor_type_orig = NULL;
  args_info->anchor_length_arg = 20;
  args_info->anchor_length_orig = NULL;
  args_info->all_to_all_flag = 0;
  args_info->chainx_flag = 0;
  args_info->chainx_opt_flag = 0;
  args_info->output_arg = NULL;
  args_info->output_orig = NULL;
  args_info->sam_arg = NULL;
  args_info->sam_orig = NULL;
  args_info->store_SAM_sequence_flag = 0;
  args_info->chainx_original_magic_numbers_flag = 0;
  args_info->custom_anchors_arg = NULL;
  args_info->custom_anchors_orig = NULL;
  args_info->random_anchors_arg = -1;
  args_info->random_anchors_orig = NULL;
  args_info->debug_case_two_output_file_arg = gengetopt_strdup ("");
  args_info->debug_case_two_output_file_orig = NULL;
  args_info->random_seed_arg = -1;
  args_info->random_seed_orig = NULL;
  
}

static
void init_args_info(struct gengetopt_args_info *args_info)
{


  args_info->help_help = gengetopt_args_info_help[0] ;
  args_info->version_help = gengetopt_args_info_help[1] ;
  args_info->text_help = gengetopt_args_info_help[2] ;
  args_info->query_help = gengetopt_args_info_help[3] ;
  args_info->mode_help = gengetopt_args_info_help[4] ;
  args_info->anchor_type_help = gengetopt_args_info_help[5] ;
  args_info->anchor_length_help = gengetopt_args_info_help[6] ;
  args_info->all_to_all_help = gengetopt_args_info_help[7] ;
  args_info->chainx_help = gengetopt_args_info_help[8] ;
  args_info->chainx_opt_help = gengetopt_args_info_help[9] ;
  args_info->output_help = gengetopt_args_info_help[10] ;
  args_info->sam_help = gengetopt_args_info_help[11] ;
  args_info->store_SAM_sequence_help = gengetopt_args_info_help[12] ;
  args_info->chainx_original_magic_numbers_help = gengetopt_args_info_help[13] ;
  args_info->custom_anchors_help = gengetopt_args_info_help[14] ;
  args_info->random_anchors_help = gengetopt_args_info_help[15] ;
  args_info->debug_case_two_output_file_help = gengetopt_args_info_help[16] ;
  args_info->random_seed_help = gengetopt_args_info_help[17] ;
  
}

void
cmdline_parser_print_version (void)
{
  printf ("%s %s\n",
     (strlen(CMDLINE_PARSER_PACKAGE_NAME) ? CMDLINE_PARSER_PACKAGE_NAME : CMDLINE_PARSER_PACKAGE),
     CMDLINE_PARSER_VERSION);

  if (strlen(gengetopt_args_info_versiontext) > 0)
    printf("\n%s\n", gengetopt_args_info_versiontext);
}

static void print_help_common(void)
{
	size_t len_purpose = strlen(gengetopt_args_info_purpose);
	size_t len_usage = strlen(gengetopt_args_info_usage);

	if (len_usage > 0) {
		printf("%s\n", gengetopt_args_info_usage);
	}
	if (len_purpose > 0) {
		printf("%s\n", gengetopt_args_info_purpose);
	}

	if (len_usage || len_purpose) {
		printf("\n");
	}

	if (strlen(gengetopt_args_info_description) > 0) {
		printf("%s\n\n", gengetopt_args_info_description);
	}
}

void
cmdline_parser_print_help (void)
{
  int i = 0;
  print_help_common();
  while (gengetopt_args_info_help[i])
    printf("%s\n", gengetopt_args_info_help[i++]);
}

void
cmdline_parser_init (struct gengetopt_args_info *args_info)
{
  clear_given (args_info);
  clear_args (args_info);
  init_args_info (args_info);

  args_info->inputs = 0;
  args_info->inputs_num = 0;
}

void
cmdline_parser_params_init(struct cmdline_parser_params *params)
{
  if (params)
    { 
      params->override = 0;
      params->initialize = 1;
      params->check_required = 1;
      params->check_ambiguity = 0;
      params->print_errors = 1;
    }
}

struct cmdline_parser_params *
cmdline_parser_params_create(void)
{
  struct cmdline_parser_params *params = 
    (struct cmdline_parser_params *)malloc(sizeof(struct cmdline_parser_params));
  cmdline_parser_params_init(params);  
  return params;
}

static void
free_string_field (char **s)
{
  if (*s)
    {
      free (*s);
      *s = 0;
    }
}


static void
cmdline_parser_release (struct gengetopt_args_info *args_info)
{
  unsigned int i;
  free_string_field (&(args_info->text_arg));
  free_string_field (&(args_info->text_orig));
  free_string_field (&(args_info->query_arg));
  free_string_field (&(args_info->query_orig));
  free_string_field (&(args_info->mode_arg));
  free_string_field (&(args_info->mode_orig));
  free_string_field (&(args_info->anchor_type_arg));
  free_string_field (&(args_info->anchor_type_orig));
  free_string_field (&(args_info->anchor_length_orig));
  free_string_field (&(args_info->output_arg));
  free_string_field (&(args_info->output_orig));
  free_string_field (&(args_info->sam_arg));
  free_string_field (&(args_info->sam_orig));
  free_string_field (&(args_info->custom_anchors_arg));
  free_string_field (&(args_info->custom_anchors_orig));
  free_string_field (&(args_info->random_anchors_orig));
  free_string_field (&(args_info->debug_case_two_output_file_arg));
  free_string_field (&(args_info->debug_case_two_output_file_orig));
  free_string_field (&(args_info->random_seed_orig));
  
  
  for (i = 0; i < args_info->inputs_num; ++i)
    free (args_info->inputs [i]);

  if (args_info->inputs_num)
    free (args_info->inputs);

  clear_given (args_info);
}


static void
write_into_file(FILE *outfile, const char *opt, const char *arg, const char *values[])
{
  FIX_UNUSED (values);
  if (arg) {
    fprintf(outfile, "%s=\"%s\"\n", opt, arg);
  } else {
    fprintf(outfile, "%s\n", opt);
  }
}


int
cmdline_parser_dump(FILE *outfile, struct gengetopt_args_info *args_info)
{
  int i = 0;

  if (!outfile)
    {
      fprintf (stderr, "%s: cannot dump options to stream\n", CMDLINE_PARSER_PACKAGE);
      return EXIT_FAILURE;
    }

  if (args_info->help_given)
    write_into_file(outfile, "help", 0, 0 );
  if (args_info->version_given)
    write_into_file(outfile, "version", 0, 0 );
  if (args_info->text_given)
    write_into_file(outfile, "text", args_info->text_orig, 0);
  if (args_info->query_given)
    write_into_file(outfile, "query", args_info->query_orig, 0);
  if (args_info->mode_given)
    write_into_file(outfile, "mode", args_info->mode_orig, 0);
  if (args_info->anchor_type_given)
    write_into_file(outfile, "anchor-type", args_info->anchor_type_orig, 0);
  if (args_info->anchor_length_given)
    write_into_file(outfile, "anchor-length", args_info->anchor_length_orig, 0);
  if (args_info->all_to_all_given)
    write_into_file(outfile, "all-to-all", 0, 0 );
  if (args_info->chainx_given)
    write_into_file(outfile, "chainx", 0, 0 );
  if (args_info->chainx_opt_given)
    write_into_file(outfile, "chainx-opt", 0, 0 );
  if (args_info->output_given)
    write_into_file(outfile, "output", args_info->output_orig, 0);
  if (args_info->sam_given)
    write_into_file(outfile, "sam", args_info->sam_orig, 0);
  if (args_info->store_SAM_sequence_given)
    write_into_file(outfile, "store-SAM-sequence", 0, 0 );
  if (args_info->chainx_original_magic_numbers_given)
    write_into_file(outfile, "chainx-original-magic-numbers", 0, 0 );
  if (args_info->custom_anchors_given)
    write_into_file(outfile, "custom-anchors", args_info->custom_anchors_orig, 0);
  if (args_info->random_anchors_given)
    write_into_file(outfile, "random-anchors", args_info->random_anchors_orig, 0);
  if (args_info->debug_case_two_output_file_given)
    write_into_file(outfile, "debug-case-two-output-file", args_info->debug_case_two_output_file_orig, 0);
  if (args_info->random_seed_given)
    write_into_file(outfile, "random-seed", args_info->random_seed_orig, 0);
  

  i = EXIT_SUCCESS;
  return i;
}

int
cmdline_parser_file_save(const char *filename, struct gengetopt_args_info *args_info)
{
  FILE *outfile;
  int i = 0;

  outfile = fopen(filename, "w");

  if (!outfile)
    {
      fprintf (stderr, "%s: cannot open file for writing: %s\n", CMDLINE_PARSER_PACKAGE, filename);
      return EXIT_FAILURE;
    }

  i = cmdline_parser_dump(outfile, args_info);
  fclose (outfile);

  return i;
}

void
cmdline_parser_free (struct gengetopt_args_info *args_info)
{
  cmdline_parser_release (args_info);
}

/** @brief replacement of strdup, which is not standard */
char *
gengetopt_strdup (const char *s)
{
  char *result = 0;
  if (!s)
    return result;

  result = (char*)malloc(strlen(s) + 1);
  if (result == (char*)0)
    return (char*)0;
  strcpy(result, s);
  return result;
}

int
cmdline_parser (int argc, char **argv, struct gengetopt_args_info *args_info)
{
  return cmdline_parser2 (argc, argv, args_info, 0, 1, 1);
}

int
cmdline_parser_ext (int argc, char **argv, struct gengetopt_args_info *args_info,
                   struct cmdline_parser_params *params)
{
  int result;
  result = cmdline_parser_internal (argc, argv, args_info, params, 0);

  if (result == EXIT_FAILURE)
    {
      cmdline_parser_free (args_info);
      exit (EXIT_FAILURE);
    }
  
  return result;
}

int
cmdline_parser2 (int argc, char **argv, struct gengetopt_args_info *args_info, int override, int initialize, int check_required)
{
  int result;
  struct cmdline_parser_params params;
  
  params.override = override;
  params.initialize = initialize;
  params.check_required = check_required;
  params.check_ambiguity = 0;
  params.print_errors = 1;

  result = cmdline_parser_internal (argc, argv, args_info, &params, 0);

  if (result == EXIT_FAILURE)
    {
      cmdline_parser_free (args_info);
      exit (EXIT_FAILURE);
    }
  
  return result;
}

int
cmdline_parser_required (struct gengetopt_args_info *args_info, const char *prog_name)
{
  FIX_UNUSED (args_info);
  FIX_UNUSED (prog_name);
  return EXIT_SUCCESS;
}


static char *package_name = 0;

/**
 * @brief updates an option
 * @param field the generic pointer to the field to update
 * @param orig_field the pointer to the orig field
 * @param field_given the pointer to the number of occurrence of this option
 * @param prev_given the pointer to the number of occurrence already seen
 * @param value the argument for this option (if null no arg was specified)
 * @param possible_values the possible values for this option (if specified)
 * @param default_value the default value (in case the option only accepts fixed values)
 * @param arg_type the type of this option
 * @param check_ambiguity @see cmdline_parser_params.check_ambiguity
 * @param override @see cmdline_parser_params.override
 * @param no_free whether to free a possible previous value
 * @param multiple_option whether this is a multiple option
 * @param long_opt the corresponding long option
 * @param short_opt the corresponding short option (or '-' if none)
 * @param additional_error possible further error specification
 */
static
int update_arg(void *field, char **orig_field,
               unsigned int *field_given, unsigned int *prev_given, 
               char *value, const char *possible_values[],
               const char *default_value,
               cmdline_parser_arg_type arg_type,
               int check_ambiguity, int override,
               int no_free, int multiple_option,
               const char *long_opt, char short_opt,
               const char *additional_error)
{
  char *stop_char = 0;
  const char *val = value;
  int found;
  char **string_field;
  FIX_UNUSED (field);

  stop_char = 0;
  found = 0;

  if (!multiple_option && prev_given && (*prev_given || (check_ambiguity && *field_given)))
    {
      if (short_opt != '-')
        fprintf (stderr, "%s: `--%s' (`-%c') option given more than once%s\n", 
               package_name, long_opt, short_opt,
               (additional_error ? additional_error : ""));
      else
        fprintf (stderr, "%s: `--%s' option given more than once%s\n", 
               package_name, long_opt,
               (additional_error ? additional_error : ""));
      return 1; /* failure */
    }

  FIX_UNUSED (default_value);
    
  if (field_given && *field_given && ! override)
    return 0;
  if (prev_given)
    (*prev_given)++;
  if (field_given)
    (*field_given)++;
  if (possible_values)
    val = possible_values[found];

  switch(arg_type) {
  case ARG_FLAG:
    *((int *)field) = !*((int *)field);
    break;
  case ARG_INT:
    if (val) *((int *)field) = strtol (val, &stop_char, 0);
    break;
  case ARG_LONG:
    if (val) *((long *)field) = (long)strtol (val, &stop_char, 0);
    break;
  case ARG_STRING:
    if (val) {
      string_field = (char **)field;
      if (!no_free && *string_field)
        free (*string_field); /* free previous string */
      *string_field = gengetopt_strdup (val);
    }
    break;
  default:
    break;
  };

  /* check numeric conversion */
  switch(arg_type) {
  case ARG_INT:
  case ARG_LONG:
    if (val && !(stop_char && *stop_char == '\0')) {
      fprintf(stderr, "%s: invalid numeric value: %s\n", package_name, val);
      return 1; /* failure */
    }
    break;
  default:
    ;
  };

  /* store the original value */
  switch(arg_type) {
  case ARG_NO:
  case ARG_FLAG:
    break;
  default:
    if (value && orig_field) {
      if (no_free) {
        *orig_field = value;
      } else {
        if (*orig_field)
          free (*orig_field); /* free previous string */
        *orig_field = gengetopt_strdup (value);
      }
    }
  };

  return 0; /* OK */
}


int
cmdline_parser_internal (
  int argc, char **argv, struct gengetopt_args_info *args_info,
                        struct cmdline_parser_params *params, const char *additional_error)
{
  int c;	/* Character of the parsed option.  */

  int error_occurred = 0;
  struct gengetopt_args_info local_args_info;
  
  int override;
  int initialize;
  int check_required;
  int check_ambiguity;
  
  package_name = argv[0];
  
  /* TODO: Why is this here? It is not used anywhere. */
  override = params->override;
  FIX_UNUSED(override);

  initialize = params->initialize;
  check_required = params->check_required;

  /* TODO: Why is this here? It is not used anywhere. */
  check_ambiguity = params->check_ambiguity;
  FIX_UNUSED(check_ambiguity);

  if (initialize)
    cmdline_parser_init (args_info);

  cmdline_parser_init (&local_args_info);

  optarg = 0;
  optind = 0;
  opterr = params->print_errors;
  optopt = '?';

  while (1)
    {
      int option_index = 0;

      static struct option long_options[] = {
        { "help",	0, NULL, 'h' },
        { "version",	0, NULL, 'V' },
        { "text",	1, NULL, 't' },
        { "query",	1, NULL, 'q' },
        { "mode",	1, NULL, 'm' },
        { "anchor-type",	1, NULL, 'a' },
        { "anchor-length",	1, NULL, 'l' },
        { "all-to-all",	0, NULL, 0 },
        { "chainx",	0, NULL, 0 },
        { "chainx-opt",	0, NULL, 0 },
        { "output",	1, NULL, 'o' },
        { "sam",	1, NULL, 0 },
        { "store-SAM-sequence",	0, NULL, 0 },
        { "chainx-original-magic-numbers",	0, NULL, 0 },
        { "custom-anchors",	1, NULL, 0 },
        { "random-anchors",	1, NULL, 0 },
        { "debug-case-two-output-file",	1, NULL, 'g' },
        { "random-seed",	1, NULL, 'r' },
        { 0,  0, 0, 0 }
      };

      c = getopt_long (argc, argv, "hVt:q:m:a:l:o:g:r:", long_options, &option_index);

      if (c == -1) break;	/* Exit from `while (1)' loop.  */

      switch (c)
        {
        case 'h':	/* Print help and exit.  */
          cmdline_parser_print_help ();
          cmdline_parser_free (&local_args_info);
          exit (EXIT_SUCCESS);

        case 'V':	/* Print version and exit.  */
          cmdline_parser_print_version ();
          cmdline_parser_free (&local_args_info);
          exit (EXIT_SUCCESS);

        case 't':	/* Reference(s) file.  */
        
        
          if (update_arg( (void *)&(args_info->text_arg), 
               &(args_info->text_orig), &(args_info->text_given),
              &(local_args_info.text_given), optarg, 0, 0, ARG_STRING,
              check_ambiguity, override, 0, 0,
              "text", 't',
              additional_error))
            goto failure;
        
          break;
        case 'q':	/* Query sequences file.  */
        
        
          if (update_arg( (void *)&(args_info->query_arg), 
               &(args_info->query_orig), &(args_info->query_given),
              &(local_args_info.query_given), optarg, 0, 0, ARG_STRING,
              check_ambiguity, override, 0, 0,
              "query", 'q',
              additional_error))
            goto failure;
        
          break;
        case 'm':	/* Chaining mode (global/semiglobal).  */
        
        
          if (update_arg( (void *)&(args_info->mode_arg), 
               &(args_info->mode_orig), &(args_info->mode_given),
              &(local_args_info.mode_given), optarg, 0, "global", ARG_STRING,
              check_ambiguity, override, 0, 0,
              "mode", 'm',
              additional_error))
            goto failure;
        
          break;
        case 'a':	/* (MUM/MEM).  */
        
        
          if (update_arg( (void *)&(args_info->anchor_type_arg), 
               &(args_info->anchor_type_orig), &(args_info->anchor_type_given),
              &(local_args_info.anchor_type_given), optarg, 0, "MUM", ARG_STRING,
              check_ambiguity, override, 0, 0,
              "anchor-type", 'a',
              additional_error))
            goto failure;
        
          break;
        case 'l':	/* Minimum anchor length.  */
        
        
          if (update_arg( (void *)&(args_info->anchor_length_arg), 
               &(args_info->anchor_length_orig), &(args_info->anchor_length_given),
              &(local_args_info.anchor_length_given), optarg, 0, "20", ARG_INT,
              check_ambiguity, override, 0, 0,
              "anchor-length", 'l',
              additional_error))
            goto failure;
        
          break;
        case 'o':	/* Output each optimal chain in MUMmer-like format {ref start, query start, length} (1-based).  */
        
        
          if (update_arg( (void *)&(args_info->output_arg), 
               &(args_info->output_orig), &(args_info->output_given),
              &(local_args_info.output_given), optarg, 0, 0, ARG_STRING,
              check_ambiguity, override, 0, 0,
              "output", 'o',
              additional_error))
            goto failure;
        
          break;
        case 'g':	/* Visualize case 2 in this file (BMP format).  */
        
        
          if (update_arg( (void *)&(args_info->debug_case_two_output_file_arg), 
               &(args_info->debug_case_two_output_file_orig), &(args_info->debug_case_two_output_file_given),
              &(local_args_info.debug_case_two_output_file_given), optarg, 0, "", ARG_STRING,
              check_ambiguity, override, 0, 0,
              "debug-case-two-output-file", 'g',
              additional_error))
            goto failure;
        
          break;
        case 'r':	/* Seed for the PRNG (-1 is different at every invocation).  */
        
        
          if (update_arg( (void *)&(args_info->random_seed_arg), 
               &(args_info->random_seed_orig), &(args_info->random_seed_given),
              &(local_args_info.random_seed_given), optarg, 0, "-1", ARG_INT,
              check_ambiguity, override, 0, 0,
              "random-seed", 'r',
              additional_error))
            goto failure;
        
          break;

        case 0:	/* Long option with no short option */
          /* Pairwise comparisons (queries).  */
          if (strcmp (long_options[option_index].name, "all-to-all") == 0)
          {
          
          
            if (update_arg((void *)&(args_info->all_to_all_flag), 0, &(args_info->all_to_all_given),
                &(local_args_info.all_to_all_given), optarg, 0, 0, ARG_FLAG,
                check_ambiguity, override, 1, 0, "all-to-all", '-',
                additional_error))
              goto failure;
          
          }
          /* Chain with at-cg/ChainX original algorithm.  */
          else if (strcmp (long_options[option_index].name, "chainx") == 0)
          {
          
          
            if (update_arg((void *)&(args_info->chainx_flag), 0, &(args_info->chainx_given),
                &(local_args_info.chainx_given), optarg, 0, 0, ARG_FLAG,
                check_ambiguity, override, 1, 0, "chainx", '-',
                additional_error))
              goto failure;
          
          }
          /* Chain with algbio/ChainX optimal algorithm.  */
          else if (strcmp (long_options[option_index].name, "chainx-opt") == 0)
          {
          
          
            if (update_arg((void *)&(args_info->chainx_opt_flag), 0, &(args_info->chainx_opt_given),
                &(local_args_info.chainx_opt_given), optarg, 0, 0, ARG_FLAG,
                check_ambiguity, override, 1, 0, "chainx-opt", '-',
                additional_error))
              goto failure;
          
          }
          /* Output approximate alignment based on the optimal chain (SAM format).  */
          else if (strcmp (long_options[option_index].name, "sam") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->sam_arg), 
                 &(args_info->sam_orig), &(args_info->sam_given),
                &(local_args_info.sam_given), optarg, 0, 0, ARG_STRING,
                check_ambiguity, override, 0, 0,
                "sam", '-',
                additional_error))
              goto failure;
          
          }
          /* Store the query sequence in the SAM output.  */
          else if (strcmp (long_options[option_index].name, "store-SAM-sequence") == 0)
          {
          
          
            if (update_arg((void *)&(args_info->store_SAM_sequence_flag), 0, &(args_info->store_SAM_sequence_given),
                &(local_args_info.store_SAM_sequence_given), optarg, 0, 0, ARG_FLAG,
                check_ambiguity, override, 1, 0, "store-SAM-sequence", '-',
                additional_error))
              goto failure;
          
          }
          /* In ChainX mode, use original magic numbers B = 100, alpha = 4 instead of variable B >= 100, alpha = 4.  */
          else if (strcmp (long_options[option_index].name, "chainx-original-magic-numbers") == 0)
          {
          
          
            if (update_arg((void *)&(args_info->chainx_original_magic_numbers_flag), 0, &(args_info->chainx_original_magic_numbers_given),
                &(local_args_info.chainx_original_magic_numbers_given), optarg, 0, 0, ARG_FLAG,
                check_ambiguity, override, 1, 0, "chainx-original-magic-numbers", '-',
                additional_error))
              goto failure;
          
          }
          /* Do not index/query but read the anchors from this file (NB it should respect the same order as query file).  */
          else if (strcmp (long_options[option_index].name, "custom-anchors") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->custom_anchors_arg), 
                 &(args_info->custom_anchors_orig), &(args_info->custom_anchors_given),
                &(local_args_info.custom_anchors_given), optarg, 0, 0, ARG_STRING,
                check_ambiguity, override, 0, 0,
                "custom-anchors", '-',
                additional_error))
              goto failure;
          
          }
          /* Number of random anchors to generate.  */
          else if (strcmp (long_options[option_index].name, "random-anchors") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->random_anchors_arg), 
                 &(args_info->random_anchors_orig), &(args_info->random_anchors_given),
                &(local_args_info.random_anchors_given), optarg, 0, "-1", ARG_LONG,
                check_ambiguity, override, 0, 0,
                "random-anchors", '-',
                additional_error))
              goto failure;
          
          }
          
          break;
        case '?':	/* Invalid option.  */
          /* `getopt_long' already printed an error message.  */
          goto failure;

        default:	/* bug: option not considered.  */
          fprintf (stderr, "%s: option unknown: %c%s\n", CMDLINE_PARSER_PACKAGE, c, (additional_error ? additional_error : ""));
          abort ();
        } /* switch */
    } /* while */



	FIX_UNUSED(check_required);

  cmdline_parser_release (&local_args_info);

  if ( error_occurred )
    return (EXIT_FAILURE);

  if (optind < argc)
    {
      int i = 0 ;
      int found_prog_name = 0;
      /* whether program name, i.e., argv[0], is in the remaining args
         (this may happen with some implementations of getopt,
          but surely not with the one included by gengetopt) */

      i = optind;
      while (i < argc)
        if (argv[i++] == argv[0]) {
          found_prog_name = 1;
          break;
        }
      i = 0;

      args_info->inputs_num = argc - optind - found_prog_name;
      args_info->inputs =
        (char **)(malloc ((args_info->inputs_num)*sizeof(char *))) ;
      while (optind < argc)
        if (argv[optind++] != argv[0])
          args_info->inputs[ i++ ] = gengetopt_strdup (argv[optind-1]) ;
    }

  return 0;

failure:
  
  cmdline_parser_release (&local_args_info);
  return (EXIT_FAILURE);
}
/* vim: set ft=c noet ts=8 sts=8 sw=8 tw=80 nojs spell : */
